import streamlit as st
import glob
import pandas as pd
import numpy as np
import pickle
import joblib
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer


movie_lis = pickle.load(open('user_final_rating_dt.pkl', 'rb'))
movies = pd.DataFrame(movie_lis)
st.title("Recommendation System")


def load_model(model_file):
    model = joblib.load(open('logit_model.joblib', 'rb'))
    return model


clf = load_model('logit_model.pkl')

df_prod_review = pd.read_pickle('df_prod_review_dict.pkl')

df_prod_review = pd.DataFrame(df_prod_review)

X_train = pd.read_pickle('X_train.pkl')
X_train = pd.DataFrame(X_train)
X_train = list(X_train[0])

word_vectorizer = TfidfVectorizer(strip_accents='unicode', token_pattern=r'\w{1,}', ngram_range=(1, 3),
                                  stop_words='english',
                                  sublinear_tf=True, max_df=0.80, min_df=0.01)
# word_vectorizer.fit(X_train)
X_train_trans = word_vectorizer.fit_transform(X_train)
l = ['joshua',
     'rebecca',
     'samantha',
     'nicole',
     'karen',
     'amanda',
     'michelle',
     'danielle',
     'momof2',
     'jayjay',
     'toni',
     'petals66',
     'judy',
     'jennifer',
     'rick',
     'george',
     'laura',
     'jill',
     'rosie',
     'disappointed',
     'shell',
     'betty',
     'paula',
     'cj',
     'deb',
     'brandon',
     'matt',
     'marty',
     'sue',
     'chris',
     'linda',
     'sandi',
     'jody',
     'sandy',
     'nick',
     'kim',
     'bill',
     'tony',
     'lisa',
     'megan',
     'dee',
     'none',
     'mary',
     'bobby',
     'happy',
     'janice',
     'holly',
     'cindy',
     'ally',
     'chrissy',
     'susan',
     'peggy',
     'angel',
     'mike',
     'patty',
     'helen',
     'danny',
     'amber',
     'kimberly',
     'michael',
     'shelly',
     'alexis',
     'charles',
     'john',
     'shopper',
     'momof3',
     'ghost',
     'frankie',
     'missy',
     'steve',
     'heather',
     'james',
     'scott',
     'brian',
     'alex',
     'mark',
     'woody',
     'jimmy',
     'jojo',
     'bigdaddy',
     'justin',
     'jason',
     'jimbo',
     'peanut',
     'david',
     'ashley',
     'steph',
     'jackie',
     'charlie',
     'aaron',
     'movielover',
     'chas',
     'dave',
     'vicki',
     'mikey',
     'ryan',
     'tina',
     'junior',
     '1234',
     'nate',
     'gary',
     'nikki',
     'angie',
     'jean',
     'sheila',
     'joel',
     'jessica',
     'mouse',
     'kyle',
     'jess',
     'jssmith',
     'raul',
     'josh',
     'thatguy',
     'jake',
     'grace',
     'sassy',
     'keith',
     'drew',
     'coco',
     'vickie',
     'annie',
     'nina',
     'jessie',
     'mimi',
     'jack',
     'trisha',
     'kris',
     'jeff',
     'diane',
     'gina',
     'moviefan',
     'sparky',
     'frank',
     'bunny',
     'nana',
     'gigi',
     'beth',
     'todd',
     'terry',
     'sissy',
     'mommy',
     'jenn',
     'meme',
     'rusty',
     'snoopy',
     'susie',
     'joey',
     'tiff',
     'jane',
     'robby',
     'anne',
     'april',
     'tammy',
     'jules',
     'spunky',
     'sharon',
     'awesome',
     'sammy',
     'lori',
     'carol',
     'donna',
     'ronda',
     'rocky',
     'wendy',
     'michele',
     'kathie',
     'diana',
     'patti',
     'adam',
     'phil',
     'maureen',
     'andy',
     'teresa',
     'momofthree',
     'mack',
     'bubba',
     'sarah',
     'nanc',
     'melissa',
     'thomas',
     'moviebuff',
     'kathy',
     'manny',
     'movieguy',
     'robert',
     'eric',
     'amazing',
     'kenny',
     'wally',
     'momma',
     'carrie',
     'rich',
     'joseph',
     'yummy',
     'chels',
     'stacy',
     'noname',
     'cool',
     'viewer',
     'debb',
     'mama',
     'roxy',
     'nanna',
     'connie',
     'baker',
     'grandma',
     'cass',
     'erin',
     'christine',
     'beth74',
     'missaye1231',
     'loris',
     'holly15',
     'leslie316',
     'tootsie23',
     'adriana9999',
     'heatherking64',
     'supergirl',
     'couponmom1996',
     'paige',
     'katdean',
     'jerri',
     'mikeh',
     'unicorn351',
     'izzy',
     'hazel',
     'debster',
     'aj1135',
     'rachael',
     'staci',
     'cricket',
     'island girl',
     'anita',
     'adma2',
     'tara',
     'sherry',
     'debbie',
     'granny',
     'kate',
     'jenny',
     'cowboy',
     'byamazon customer',
     'bykindle customer',
     'chuck',
     'andrea',
     'kevman79',
     'wildman',
     'emily',
     'stacey',
     'pepper',
     'paul',
     'andrew',
     'shadow',
     'dusty']


@st.cache_data
def find_top_recommendations(pred_rating_df, userid, topn):
    recommendation = pred_rating_df.loc[userid].sort_values(ascending=False)[0:topn]
    recommendation = pd.DataFrame(recommendation).reset_index().rename(columns={userid: 'predicted_ratings'})
    return recommendation


@st.cache_data
def get_sentiment_product(x):
    ## Get review list for given product
    product_name_review_list = df_prod_review[df_prod_review['prod_name'] == x]['Review'].tolist()
    ## Transform review list into DTM (Document/review Term Matrix)
    features = word_vectorizer.transform(product_name_review_list)
    ## Predict sentiment
    return (clf.predict(features)).mean()


@st.cache_resource
def find_top_pos_recommendation(user_final_rating, user_input, _df_prod_review, _word_vectorizer, no_recommendation):
    recommendation_user_user = find_top_recommendations(user_final_rating, user_input, 10)
    # st.write('------',recommendation_user_user['index'])
    #recommendation_user_user['userId'] = user_input
    ## filter out recommendations where predicted rating is zero
    # recommendation_user_user = recommendation_user_user[recommendation_user_user['predicted_ratings'] != 0]
    st.write("Recommended products for user id: ", user_input, " without using sentiment")
    st.write(recommendation_user_user)
    rec_user_user = recommendation_user_user
    ## Get overall sentiment score for each recommended product
    recommendation_user_user['sentiment_score'] = recommendation_user_user['index'].apply(get_sentiment_product)
    ## Transform scale of sentiment so that it can be manipulated with predicted rating score
    scaler = MinMaxScaler(feature_range=(1, 5))
    scaler.fit(recommendation_user_user[['sentiment_score']])
    recommendation_user_user['sentiment_score'] = scaler.transform(recommendation_user_user[['sentiment_score']])
    ## Get final product ranking score using 1*Predicted rating of recommended product + 2*normalized sentiment score on scale of 1–5 of recommended product
    recommendation_user_user['combined_product_score'] = 1 * recommendation_user_user['predicted_ratings'] + \
                                                        2 * recommendation_user_user['sentiment_score']
    st.write("Recommended products for user id: ", user_input, " after using sentiment")
    ## Sort product ranking score in descending order and show only top `no_recommendation`
    st.write(recommendation_user_user.sort_values(by=['combined_product_score'], ascending=False).head(no_recommendation))
    return (rec_user_user,
            recommendation_user_user.sort_values(by=['combined_product_score'], ascending=False).head(no_recommendation))


op2 = st.selectbox(label="Select user...", options=l)
dff1, dff2 = find_top_pos_recommendation(movies, op2, df_prod_review, word_vectorizer, 5)

j = pd.DataFrame(np.array(['Pink Friday: Roman Reloaded Re-Up (w/dvd)',
                           'Dark Shadows (includes Digital Copy) (ultraviolet) (dvdvideo)',
                           'Red (special Edition) (dvdvideo)',
                           'Smead174 Recycled Letter Size Manila File Backs W/prong Fasteners, 2 Capacity, 100/box',
                           "Cheetos Crunchy Flamin' Hot Cheese Flavored Snacks",
                           'K-Y Love Sensuality Pleasure Gel',
                           'Olay Regenerist Deep Hydration Regenerating Cream',
                           'Hormel Chili, No Beans',
                           'Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total',
                           'Tostitos Bite Size Tortilla Chips',
                           'Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd)',
                           "Mrs. Meyer's Lemon Verbena Surface Scrub",
                           'Mike Dave Need Wedding Dates (dvd + Digital)',
                           'Coty Airspun Face Powder, Translucent Extra Coverage',
                           'The Honest Company Laundry Detergent',
                           'Hoover174 Platinum Collection153 Lightweight Bagged Upright Vacuum With Canister - Uh30010com',
                           'Boraam Sonoma Kitchen Cart With Wire Brush Gray - Maaya Home',
                           "There's Something About Mary (dvd)",
                           'Bisquick Original Pancake And Baking Mix - 40oz',
                           'Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd',
                           'J.R. Watkins Hand Cream, Lemon Cream',
                           'My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Digital)',
                           'The Resident Evil Collection 5 Discs (blu-Ray)',
                           'Ambi Complexion Cleansing Bar',
                           'Aussie Aussome Volume Shampoo, 13.5 Oz',
                           "Chester's Cheese Flavored Puffcorn Snacks",
                           'Trend Lab Park Nursing Cover - Paisley',
                           "Johnson's Baby Bubble Bath and Wash, 15oz",
                           'Windex Original Glass Cleaner Refill 67.6oz (2 Liter)',
                           'Clorox Disinfecting Bathroom Cleaner',
                           'Chips Ahoy! Original Chocolate Chip - Cookies - Family Size 18.2oz',
                           'Nexxus Exxtra Gel Style Creation Sculptor',
                           "Stargate (ws) (ultimate Edition) (director's Cut) (dvdvideo)",
                           'CeraVe SA Renewing Cream', "Burt's Bees Lip Shimmer, Raisin",
                           'Hawaiian Punch Berry Limeade Blast Juice',
                           'Head & Shoulders Classic Clean Conditioner',
                           "Stacy's Simply Naked Bagel Chips",
                           'Cuisinart174 Electric Juicer - Stainless Steel Cje-1000',
                           "Various - Country's Greatest Gospel:Gold Ed (cd)",
                           'Cococare 100% Natural Castor Oil',
                           'Tresemme Kertatin Smooth Infusing Conditioning',
                           '100:Complete First Season (blu-Ray)',
                           'Lynk Professional174 Pull Out Cutting Board Bakeware Sliding Cabinet Organizer',
                           "Cars Toon: Mater's Tall Tales",
                           'Suave Professionals Hair Conditioner, Sleek',
                           'Clear Scalp & Hair Therapy Total Care Nourishing Shampoo',
                           'Neutrogena Wet Skin Sunscreen Spray Broad Spectrum SPF 50, 5oz',
                           'Tai Pei Sweet & Sour Chicken',
                           'Just For Men Touch Of Gray Gray Hair Treatment, Black T-55',
                           'Lysol Concentrate Deodorizing Cleaner, Original Scent',
                           'Pendaflex174 Divide It Up File Folder, Multi Section, Letter, Assorted, 12/pack',
                           'Stander Pt Bedcane - Bed Handle',
                           "Jason Aldean - They Don't Know",
                           'Pleasant Hearth 1,800 sq ft Wood Burning Stove with Blower, Medium, LWS-127201',
                           'Finish Quantum Dishwasher Detergent, Lemon Sparkle Scent, 45 Count',
                           'Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter',
                           'Feit 60-Watt A19 Gu24 Base Led Light Bulb - Soft White',
                           'Ceiling Fan With Light White 14.2 X 29.9 X 9.2 - Hunter Fan',
                           'Storkcraft Tuscany Glider and Ottoman, Beige Cushions, Espresso Finish',
                           'Sea Gull Lighting Six Light Bath Sconce/vanity - Brushed Nickel',
                           'Diet Canada Dry Ginger Ale - 12pk/12 Fl Oz Cans',
                           'Vaseline Intensive Care Healthy Hands Stronger Nails',
                           'Cantu Coconut Milk Shine Hold Mist - 8oz',
                           'Chobani174 Strawberry On The Bottom Non-Fat Greek Yogurt - 5.3oz',
                           "L'oreal Paris Visible Lift Smooth Absolute, Natural Buff",
                           'Pantene Pro-V Expert Collection Age Defy Conditioner',
                           'Chex Muddy Buddies Brownie Supreme Snack Mix',
                           'Bounce Dryer Sheets, Fresh Linen, 160 sheets',
                           'Pleasant Hearth Diamond Fireplace Screen - Espresso',
                           'Bilbao Nightstand Gray Oak - South Shore',
                           'Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz',
                           'Pleasant Hearth 7.5 Steel Grate, 30 5 Bar - Black',
                           "Chips Deluxe Soft 'n Chewy Cookies",
                           "Newman's Own Balsamic Vinaigrette, 16.0oz",
                           'Caress Moisturizing Body Bar Natural Silk, 4.75oz',
                           'Ragu Traditional Pasta Sauce',
                           'Vaseline Intensive Care Lip Therapy Cocoa Butter',
                           'Barielle Nail Rebuilding Protein',
                           'Kind Dark Chocolate Chunk Gluten Free Granola Bars - 5 Count',
                           'Ragu Roasted Garlic Parmesan Pasta Sauce',
                           'Leslie Sansone:Belly Blasting Walk (dvd)',
                           'Post Bound Jumbo Album - Burgundy (11x14)',
                           'Australian Gold Exotic Blend Lotion, SPF 4',
                           "Meguiar's Deep Crystal Car Wash 64-Oz.",
                           'Banana Boat Sunless Summer Color Self Tanning Lotion, Light To Medium',
                           'Tostitos Simply Blue Corn Tortilla Chips',
                           'Meguiars Interior Detailer Wipes 25ct',
                           'Yes To Grapefruit Rejuvenating Body Wash',
                           'Cetaphil Gentle Skin Cleanser, 2oz',
                           'Shea Moisture Mango & Carrot Kids Extra-Nourishing Conditioner, 8fl Oz',
                           'Way Basics 3-Shelf Eco Narrow Bookcase Storage Shelf, Espresso - Formaldehyde Free - Lifetime Guarantee',
                           'Yes To Carrots Nourishing Body Wash',
                           'Power Crunch Protein Energy Bar Peanut Butter Creme Original',
                           "Meguiar's Ultimate Quik Detailer 22-Oz.",
                           'Happy Tot Apple and Butternut Squash',
                           'Holmes174 Personal Indoor Heater W/ Manual Controls White 1500w Hfh131-N',
                           'Jolly Time Select Premium Yellow Pop Corn',
                           'Doc Mcstuffins: Friendship Is The Best Medicine',
                           'Vicks Vaporub, Regular, 3.53oz', 'Equals (blu-Ray)',
                           'Various - Red Hot Blue:Tribute To Cole Porter (cd)',
                           'Eagle Fat Free Sweetened Condensed Milk',
                           'Delta Single Handle Shower Faucet',
                           'Tree Hut Shea Body Butters, Coconut Lime, 7 oz',
                           'Orajel Maximum Strength Toothache Pain Relief Liquid',
                           'Iman Second To None Stick Foundation, Clay 1',
                           'Various Artists - Choo Choo Soul (cd)',
                           'Ogx Conditioner, Hydrating Teatree Mint',
                           'Black Front Loading Frame Set (8.5x11) Set Of 12',
                           'Musselman Apple Sauce, Cinnamon, 48oz',
                           'Super Poligrip Denture Adhesive Cream, Ultra Fresh - 2.4 Oz',
                           'Romantic Drama: Greatest Classic Films Collection 2 Discs',
                           'Wagan Smartac 80watt Inverter With Usb',
                           'D-Con Mice Bait Station - 3ct', 'SC Johnson One Step No Buff Wax',
                           'Care Free Curl Gold Instant Activator',
                           'Kraus FVS-1007 Single Hole Vessel Bathroom Faucet from the Ramus Collection',
                           'The Script - No Sound Without Silence (cd)',
                           "Toy Story Kids' Woody Accessory Kit",
                           'Creme Of Nature Intensive Conditioning Treatment, 32',
                           'Sopranos:Season 6 Part 1 (blu-Ray)',
                           'Solo Foods Poppy Seed Cake and Pastry Filling',
                           'Arrid Extra Dry Anti-Perspirant Deodorant Spray Regular',
                           "L'oreal Paris Colour Caresse Wet Shine Stain, Pink Resistance",
                           'Sabre 2 Pack Door And Window Alarm',
                           'Nearly Natural Pothos Ledge Plant (set On Foam) Silk Plant',
                           'Progresso Traditional Chicken Rice With Vegetables Soup',
                           "Nearly Natural 5.5' Bamboo W/decorative Planter",
                           "L'or233al Paris Elvive Extraordinary Clay Rebalancing Conditioner - 12.6 Fl Oz",
                           "Mrs. Meyer's174 Lemon Verbena Laundry Scent Booster - 18oz",
                           'Lundberg Organic Cinnamon Toast Rice Cakes',
                           'Heinz Tomato Ketchup, 38oz',
                           'Pantene Color Preserve Volume Shampoo, 25.4oz',
                           'Solo Foods Almond Paste',
                           'Disney174 Jake And The Neverland Pirates 4 Piece Bedding Set - Toddler',
                           'Pearhead Id Bracelet Frame',
                           'Craft Punch Giga Scallop Circle 45 24687534 To 334',
                           'Bumble Bee Solid White Albacore In Water - 5 Oz',
                           'Citrus Magic Instant Spot & Stain Remover',
                           'La Tortilla Factory Hand Made Style Tortillas Flour',
                           "Black Sister's Revenge (dvd)",
                           'The Seaweed Bath Co. Argan Conditioner, Smoothing Citrus',
                           'Bi-O-kleen Spray & Wipe All Purpose Cleaner',
                           'Alberto VO5 Salon Series Smooth Plus Sleek Shampoo',
                           'Clambake (dvd)',
                           'Sea Gull Lighting Ceiling Fan - White',
                           'Progresso Traditional Meatball & Rice Soup',
                           "Herr's Baked Cheese Curls",
                           'King Ralph (dvd)',
                           "Nature's Path Flax Plus Maple Pecan Crunch Cereal",
                           'Lite Source Basic Ii 1-Lt Floor Lamp - Dark Bronze',
                           'Sloan Royal Urinal Flush Valve, 1.0 Gpf, Royal 186-1',
                           'Sunflower Swag With Metal Frame - Nearly Natural',
                           'Maranatha No Stir Raw Maple Almond Butter',
                           'Pinaud Clubman Styling Gel, Superhold',
                           'Wedding Wishes Wedding Guest Book',
                           'Baxter Of California Cream Pomade',
                           "Newman's Own Organics Licorice Twist, Black 5oz",
                           'Plano Mini-Magnum 13-Compartment Tackle Box',
                           'Calvin Klein Secret Obsession Eau De Parfum',
                           'Wallmount Server Cabinet (450mm, 9 RU)',
                           "Udi's Pepperoni Pizza",
                           "Annie's Homegrown Gluten Free Double Chocolate Chip Granola Bars",
                           'Coola Organic Sunscreen Classic Face Cucumber SPF 30',
                           'Simple Green All-Purpose Cleaner, 16oz',
                           'Wilton Black Dots Standard Baking Cups',
                           'Avery174 11-1/4 X 9-1/4 Index Maker Extra Wide Label Dividers With 5 Tab - Clear (5 Sets Per Pack)',
                           'Lundberg Wehani Rice, 25lb',
                           'Stonyfield Yobaby Peach & Pear Yogurt 4oz 6 Ct',
                           'Charcoal Stone Toothbrush Holder Gray',
                           'Pocket Watch Wall Clock Distressed Black - Yosemite Home Decor174',
                           'Mill Creek Aloe Vera & Paba Lotion',
                           'All,bran Complete Wheat Flakes, 18 Oz.',
                           'Clorox Ultimate Care Premium Bleach',
                           'Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix',
                           '42 Dual Drop Leaf Table with 2 Madrid Chairs"',
                           'Little Bedding By Nojo Jungle Dreams 2 Pack Sheet Set',
                           'Sizzix Framelits Dies 1by Tim Holtz Bird Crazy-Silver Asst Sizes',
                           'Starbucks153 Doubleshot Protein Coffee - 11 Fl Oz',
                           'Bill Glor Gaither - Church In The Wildwood (cd)',
                           'RC Cola, 12oz',
                           'Head & Shoulders Dandruff Shampoo Ocean Lift 2 In 1',
                           'Elvis Presley - Girl Happy (cd)',
                           'Kenroy Home Table Lamp - Chrome',
                           'Dermalogica Special Cleansing Gel, 8.4oz',
                           'Smead174 3-In-1 Supertab Section Folders, 1/3 Cut Top Tab, Letter, Assorted, 12/pack',
                           "Africa's Best No-Lye Dual Conditioning Relaxer System Super",
                           'Tramontina Ceramica 10 Piece Cookware Set - Red',
                           'Carson-Dellosa Publishing Photographic Learning Cards Boxed Set, Nouns/verbs/adjectives, Grades K-12',
                           'Home Health Hairever Shampoo',
                           'Lite Source Reiko 1 Light Table Lamp - Orange',
                           'J.a. Henckels International 4-Pc Everedge Plus Steak Knife Set',
                           'Olay Moisturizing Lotion For Sensitive Skin',
                           'Kikkoman Soy Sauce, 5fl oz',
                           'Kohler 10280-4 Fort Bath Spout With Sculpted Lift Rod and 1/2-in NPT Connection',
                           'Gain Original Scent Liquid Fabric Softener 129 Oz',
                           "Burt's Bees Lip Shimmer, Watermelon",
                           'Scooby Doo And The Loch Ness Monster (blu-Ray)',
                           'Cal Lighting Led Dark Bronze Finish Metal Piano Lamp',
                           "L'oreal Paris Advanced Hairstyle Boost It High Lift Creation Spray",
                           'Plum Organics Just Prunes',
                           'Candy Pink Plastic Cups, 20 pk',
                           'JNH Lifestyles Goldstar 3 Person FAR Infrared Sauna',
                           '2x Ultra Era with Oxi Booster, 50fl oz',
                           'Reebok Classic Leather Running Shoes - White (Men)',
                           "Annie's Homegrown Deluxe Elbows & Four Cheese Sauce",
                           'Physicians Formula Mineral Wear Talc-Free Mineral Correcting Powder, Creamy Natural',
                           'Weleda Everon Lip Balm',
                           'Fiskars174 Classic Stick Rotary Cutter (45 Mm)',
                           "Fantasy Fields Lil' Sports Fan Step Stool - Teamson",
                           'Starbucks Iced Expresso Classics Vanilla Latte Coffee Beverage - 40oz',
                           'Blue Anchor Design Throw Pillow (18x18) - Rizzy Home',
                           'Kendall Comforter And Sheet Set (twin) Aqua - 7pc',
                           'Pacific Natural Foods Organic Beef Broth',
                           'Honeywell Heatbud Ceramic Heater Black',
                           'Jergens Extra Moisturizing Liquid Hand Wash, 7.5oz',
                           "Lay's Salt & Vinegar Flavored Potato Chips",
                           'Noosa Honey Yogurt',
                           '0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest',
                           'If A Man Answers (dvd)',
                           "Stacy's Garden Veggie Medley Pita Chips",
                           'Hollywood Beauty Olive Cholesterol',
                           'Southern Enterprises Archer Fold-Away Home Bar in Walnut',
                           '4C Grated Parmesan Cheese 100% Natural 8oz Shaker',
                           'Heiress (dvd)',
                           'Mia Shower Curtain Green/brown - Lush Decor174',
                           'Progresso Traditional Chicken Tuscany Soup',
                           'Progresso Light Vegetable & Noodle Soup',
                           'Maybelline Clean Express! Makeup Removing Lotion',
                           'Physicians Formula Powder Palette Mineral Glow Pearls, Translucent Pearl',
                           'Switchmas (dvd)',
                           'Voortman Sugar Free Fudge Chocolate Chip Cookies',
                           'Finish Gelpacs Dishwasher Detergent, Orange Scent, 84ct',
                           'Tim Holtz Retractable Craft Pick-Red 6x.5',
                           'Iman Luxury Moisturizing Lipstick, Black Brandy 006',
                           "Ben & Jerry's Coffee, Coffee Buzzbuzzbuzz! Ice Cream, Pint",
                           'Ogx Anti-breakage Keratin Oil 3 Minute Miraculous Recovery',
                           'Spam Single Classic',
                           'Smead174 2 1/4 Inch Accordion Expansion Wallet, Poly, Letter, Translucent Green',
                           'High-Dome Floor Door Stop',
                           'Concept Housewares 36 Natural Wood ceiling mounted pot rack',
                           'Tostitos Original Restaurant Style Tortilla Chips',
                           'Walkers Stem Ginger Shortbread',
                           'Queen Helene Cocoa Butter Solid',
                           'Bodycology Nourishing Body Cream, Pretty In Paris',
                           'Sea Gull Lighting Holman One Light Wall/bath Sconce - Brushed Nickel',
                           'Bedtime Originals Pinkie Musical Mobile',
                           '2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black'
                           ]), columns=['prod_name'])


def load_imgs(df):
    img_fil = glob.glob("images*/*.png")
    imgs = sorted(img_fil, key=lambda x: int(x.split('img (')[1].split(').png')[0]))
    view_imgs = []
    capts = []
    for i in df['index']:
        z = np.where(j['prod_name'] == i)
        z = z[0][0]
        capts.append(i)
        view_imgs.append(imgs[z])
    groups = []
    for i in range(0, len(view_imgs), 3):
        groups.append(view_imgs[i:i + 3])
    cols = st.columns(3)
    for grp in groups:
        for i, img in enumerate(grp):
            cols[i].image(img, caption=capts[i], width=200)

if st.button('Images'):
    st.write('Recommendations without using Sentiment')
    load_imgs(dff1)
    st.write('Recommendations using Sentiment')
    load_imgs(dff2)
